# use the official Ubuntu image as the base image
FROM ubuntu:latest

# set the maintainer
LABEL maintainer="soumitra"

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# update sources list and install dependencies
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    konsole \
    python3 \
    python3-pip \
    python3-pyaudio \
    alsa-utils \
    pulseaudio \
    pulseaudio-utils \
    libasound2-plugins \
    libportaudio2 \
    libportaudiocpp0 \
    python3-numpy \
    && rm -rf /var/lib/apt/lists/*

# Set up PulseAudio config
RUN mkdir -p /root/.config/pulse
RUN echo "default-server = unix:/tmp/pulseaudio.socket" > /root/.config/pulse/client.conf
RUN echo "autospawn = no" >> /root/.config/pulse/client.conf
RUN echo "daemon-binary = /bin/true" >> /root/.config/pulse/client.conf
RUN echo "enable-shm = false" >> /root/.config/pulse/client.conf

# Optional: Copy an entire directory
COPY ./22b0933_22b0982_22b0984_22b0995_CS378_lab3/ /home/soumitra/Downloads/lab3/

# Define a default command (optional)
CMD ["bash"]